namespace Kovah
{
	[HavokClass(EVersion.hk_2012_1_0_r1, typeof(hkcdDynamicTreeDynamicStorage0hkcdDynamicTreeAnisotropicMetrichkcdDynamicTreeCodecRawUint))]
	[HavokClass(EVersion.hk_2014_1_0_r1, typeof(hkcdDynamicTreeDynamicStorage0hkcdDynamicTreeAnisotropicMetrichkcdDynamicTreeCodecRawUint))]
	public partial class hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodecRawUint : hkcdDynamicTreeDynamicStorage0hkcdDynamicTreeAnisotropicMetrichkcdDynamicTreeCodecRawUint
	{
		public hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodecRawUint()
		{
		}
	}
}
