namespace Kovah
{
	[HavokClass(EVersion.hk_2012_1_0_r1, typeof(hkcdDynamicTreeDynamicStorage0hkcdDynamicTreeAnisotropicMetrichkcdDynamicTreeCodecRawUlong))]
	[HavokClass(EVersion.hk_2014_1_0_r1, typeof(hkcdDynamicTreeDynamicStorage0hkcdDynamicTreeAnisotropicMetrichkcdDynamicTreeCodecRawUlong))]
	public partial class hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodecRawUlong : hkcdDynamicTreeDynamicStorage0hkcdDynamicTreeAnisotropicMetrichkcdDynamicTreeCodecRawUlong
	{
		public hkcdDynamicTreeDefaultDynamicStoragehkcdDynamicTreeCodecRawUlong()
		{
		}
	}
}
